export enum DiagramActionType {
  CLICK_ON_GRID = 'CLICK_ON_GRID',
  ADD_GROUP = 'ADD_GROUP',
  CONTEXT_MENU_ON_STEP = 'CONTEXT_MENU_ON_STEP',
  CONTEXT_MENU_ON_GROUP = 'CONTEXT_MENU_ON_GROUP',
  ADD_STEP = 'ADD_STEP',
  CONTEXT_MENU_ON_GRID = 'CONTEXT_MENU_ON_GRID',
  ZOOM = 'ZOOM',
}
